### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by ferreirafox** [abdurrahman720/react-swipeable-button#2]
What is the correct way to reset the button to its initial state?

**Comment by ferreirafox** [comment]
Here is the code to correct it, I think it would be correct. I tried to make a commit for a PR, but it's not possible, so here it is

```
reset = () => {
    if (!this.state.unlocked) return;
    this.setState({ unlocked: false }, () => {
      this.sliderLeft = 0;
      this.updateSliderStyle();
    });
  };
```

**Comment by abdurrahman720** [comment]
Hi @ferreirafox 

Thanks for taking the time to look into this! Just a quick question—did you try forking the repo before submitting the PR?

That being said, I completely understand your request. I'll also be adding a new complete function that will allow developers to programmatically trigger the button swipe when needed. While it may not be a frequently used feature, adding this level of customization will certainly make the component more versatile and adaptable.
